---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: {{ include "workshop-pipelines.fullname" . }}
  labels:
    {{- include "workshop-pipelines.labels" . | nindent 4 }}
spec:
  finally:
    - name: update-deployment
      params:
        - name: SCRIPT
          value: 'oc set triggers deploy/workshop-pipelines --from-image=workshop-pipelines:latest -c workshop-pipelines'
        - name: VERSION
          value: latest
      taskRef:
        kind: Task
        name: openshift-client        
  params:
    - default: 'https://github.com/maximilianoPizarro/workshop-pipelines'
      name: GIT_REPO
      type: string  
    - default: 'image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/{{ include "workshop-pipelines.fullname" . }}'
      name: IMAGE_NAME
      type: string
    - default: /app
      name: PATH_CONTEXT
      type: string
    - default: 'registry.redhat.io/ubi8/openjdk-17@sha256:af305e087061cbaa4107ce0b304a1ef987f6b54bae3f75bfd529cfd084cba9b5'
      name: MAVEN_IMAGE
      type: string
    - default: ecommerce-0.0.1-SNAPSHOT.jar
      name: APP_JAR_VERSION
      type: string
  tasks:
    - name: maven
      params:
        - name: MAVEN_IMAGE
          value: 'registry.redhat.io/ubi8/openjdk-17@sha256:af305e087061cbaa4107ce0b304a1ef987f6b54bae3f75bfd529cfd084cba9b5'
        - name: GOALS
          value:
            - clean
            - verify
            - '-Pprod'
            - '-Dmaven.repo.local=$(workspaces.source.path)/$(params.PATH_CONTEXT)/.m2'
            - '-Dmaven.test.skip=true'
        - name: MAVEN_MIRROR_URL
          value: ''
        - name: SERVER_USER
          value: ''
        - name: SERVER_PASSWORD
          value: ''
        - name: PROXY_USER
          value: ''
        - name: PROXY_PASSWORD
          value: ''
        - name: PROXY_PORT
          value: ''
        - name: PROXY_HOST
          value: ''
        - name: PROXY_NON_PROXY_HOSTS
          value: ''
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: $(params.PATH_CONTEXT)
      runAfter:
        - npm
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: source
          workspace: workspace
        - name: maven-settings
          workspace: workspace
        - name: maven-local-repo
          workspace: workspace          
    - name: git-clone
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: main
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: 'registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:c4b2183f7c7997bd401d86b33eefb637b3ef2fa90618e875106292cd69a15c14'
        - name: userHome
          value: /home/git
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: npm
      params:
        - name: PATH_CONTEXT
          value: $(params.PATH_CONTEXT)
        - name: ARGS
          value:
            - install
        - name: IMAGE
          value: 'docker.io/library/node:18.18.2-alpine'
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: npm
      workspaces:
        - name: source
          workspace: workspace
    - name: s2i-binary-build
      params:
        - name: SCRIPT
          value: oc start-build {{ include "workshop-pipelines.fullname" . }} --from-file=$(workspaces.manifest-dir.path)/$(params.PATH_CONTEXT)/target/$(params.APP_JAR_VERSION) --wait
        - name: VERSION
          value: latest
      runAfter:
        - maven
      taskRef:
        kind: Task
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: workspace
    - name: promote-to-quay
      taskRef:
        name: promote-to-quay
      params:
        - name: source-image
          {{- if contains "image-registry" .Values.pipeline.sourceImage }}
          value: {{ .Values.pipeline.sourceImage }}
          {{- else }}
          {{- $sourceImage := .Values.pipeline.sourceImage }}
          {{- if contains ":" $sourceImage }}
          {{- $parts := splitList ":" $sourceImage }}
          {{- $imageName := index $parts 0 }}
          {{- $imageTag := index $parts 1 | default "latest" }}
          value: image-registry.openshift-image-registry.svc:5000/{{ .Values.namespace }}/{{ $imageName }}:{{ $imageTag }}
          {{- else }}
          value: image-registry.openshift-image-registry.svc:5000/{{ .Values.namespace }}/{{ $sourceImage }}:latest
          {{- end }}
          {{- end }}
        - name: target-image
          value: {{ .Values.pipeline.targetImage }}
      runAfter:
        - s2i-binary-build
      {{- if .Values.pipeline.promoteToQuay.retries }}
      retries: {{ .Values.pipeline.promoteToQuay.retries }}
      {{- else }}
      retries: 3
      {{- end }}
  workspaces:
    - name: workspace
    - name: credentials                           

